PGI/urls.py
from django.contrib import admin
from django.urls import path,include
from pgi_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('pgi_app/',include('pgi_app.urls')),
    path('logout/',views.user_logout,name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pgi_app/urls.py
from django.conf.urls import url
from pgi_app import views

app_name= 'pgi_app'
urlpatterns=[
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^student_profile/$',views.student_profile,name='student_profile'),
    url(r'^check_status/$',views.check_status,name='check_status'),
    url(r'^make_request/$',views.make_request,name='make_request'),
    url(r'^available_rooms/$',views.available_rooms,name='available_rooms'),
    url(r'^oi_profile/$',views.oi_profile,name='oi_profile'),
    url(r'^oi_request/$',views.oi_request,name='oi_request'),
    url(r'^si_profile/$',views.si_profile,name='si_profile'),
    url(r'^si_request/$',views.si_request,name='si_request'),
    url(r'^guard_request/$',views.guard_request,name='guard_request'),
    url(r'^guard_profile/$',views.guard_profile,name='guard_profile'),
]

pgi_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class authority_db(models.Model):
    user=models.OneToOneField(User,null=True,on_delete=models.SET_NULL)
    DESIGNATION=(
        ('Club secretary','Club secretary'),
        ('Club Office In-charge','Club Office In-charge'),
        ('Security In-charge','Security In-charge'),
        ('Guard In-charge','Guard In-charge'),
    )
    designation=models.CharField(max_length=200,null=True,choices=DESIGNATION)
    CLUB=(
        ('Computer Science Society','Computer Science Society'),
        ('Art and Photography Club','Art and Photography Club'),
        ('Dramatics Club','Dramatics Club'),
        ('Not Valid','Not Valid'),
    )
    club=models.CharField(max_length=200,null=True,choices=CLUB)
    def __str__(self):
        return self.user.username

class room_db(models.Model):
    room_number=models.CharField(max_length=200,primary_key=True)
    department=models.CharField(max_length=200,blank=True,null=True)
    def __str__(self):
        return self.room_number


class request_db(models.Model):
    request_id=models.IntegerField(default=0,primary_key=True)
    authority=models.ForeignKey(User,null=True,on_delete=models.DO_NOTHING)
    room=models.ForeignKey(room_db,on_delete=models.DO_NOTHING)
    date=models.DateField(null=True)
    SLOT=(
        ('4-5','4-5'),
        ('5-6','5-6'),
        ('6-7','6-7'),
        ('7-8','7-8'),
    )
    slot=models.CharField(max_length=200,null=True,choices=SLOT)

    STATUS=(
        ('-1','-1'),
        ('0','0'),
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
    )
    status=models.CharField(max_length=200,null=True,choices=STATUS)
    def __str__(self):
        return str(self.request_id)

pgi_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from datetime import datetime
from .models import *

rooms_dict={'Lecture Hall-1':'New Academic Block','Lecture Hall-2':'New Academic Block','Lecture Hall-3':'New Academic Block','Lecture Hall-4':'Computer Science Department','Lecture Hall-5':'Computer Science Department','Lecture Hall-6':'Computer Science Department','Lecture Hall-7':'Electronics Department','Lecture Hall-8':'Electronics Department','Lecture Hall-9':'Electronics Department','Lecture Hall-10':'Electronics Department'}

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


# Create your views here.
def index(request):
    return render(request,'pgi_app/index.html')


def user_login(request):
    if request.method=='POST':
        curr_username=request.POST.get('username')
        curr_password=request.POST.get('password')
        curr_designation=request.POST.get('designation')
        user=authenticate(username=curr_username,password=curr_password)

        if user:
            curr_user=authority_db.objects.get(user=user)
            if curr_designation==curr_user.designation:
                if user.is_active:
                    login(request,user)
                    if curr_designation=='Club secretary':
                        return student_profile(request)
                    elif curr_designation=='Club Office In-charge':
                        return oi_profile(request)
                    elif curr_designation=='Security In-charge':
                        return si_profile(request)
                    elif curr_designation=='Guard In-charge':
                        return guard_profile(request)
                else:
                    return HttpResponse("ACCOUNT NOT ACTIVE!!")
            else:
                messages.error(request,'username or password not correct')
                return HttpResponseRedirect(request.path_info)
        else:
            messages.error(request,'username or password not correct')
            return HttpResponseRedirect(request.path_info)



    return render(request,'pgi_app/user_login.html')



@login_required
def si_profile(request):
    curr_user=authority_db.objects.get(user=request.user)
    curr_mail=request.user.email
    curr_fn=request.user.first_name
    curr_ln=request.user.last_name
    #print(curr_mail,curr_club,curr_fn,curr_ln)
    my_dict={'si':curr_fn,'mail':curr_mail,'ln':curr_ln}
    return render(request,'pgi_app/si_profile.html',my_dict)






@login_required
def oi_profile(request):
    curr_user=authority_db.objects.get(user=request.user)
    curr_mail=request.user.email
    curr_fn=request.user.first_name
    curr_ln=request.user.last_name
    curr_club=curr_user.club
    #print(curr_mail,curr_club,curr_fn,curr_ln)
    my_dict={'oi':curr_fn,'club':curr_club,'mail':curr_mail,'ln':curr_ln}
    return render(request,'pgi_app/oi_profile.html',my_dict)




@login_required
def guard_profile(request):
    curr_user=authority_db.objects.get(user=request.user)
    curr_mail=request.user.email
    curr_fn=request.user.first_name
    curr_ln=request.user.last_name
    #print(curr_mail,curr_club,curr_fn,curr_ln)
    my_dict={'guard':curr_fn,'mail':curr_mail,'ln':curr_ln}
    return render(request,'pgi_app/guard_profile.html',my_dict)






@login_required
def student_profile(request):
    curr_user=authority_db.objects.get(user=request.user)
    curr_mail=request.user.email
    curr_fn=request.user.first_name
    curr_ln=request.user.last_name
    curr_club=curr_user.club
    #print(curr_mail,curr_club,curr_fn,curr_ln)
    my_dict={'secy':curr_fn,'club':curr_club,'mail':curr_mail,'ln':curr_ln,'imagee':curr_user}
    return render(request,'pgi_app/student_profile.html',my_dict)




@login_required
def check_status(request):
    curr_username=request.user.username
    requests_by_user=request_db.objects.filter(authority=request.user).exclude(status='-1')
    # if len(requests_by_user)==0:
    #     return HttpResponse('oops,you haven\'t made any bookings')
    req_dict={'requests':requests_by_user}
    if request.method=='POST':
        req_id=request.POST.get('cancel')
        req_to_cancel=request_db.objects.get(request_id=req_id)
        req_to_cancel.status='-1'
        req_to_cancel.save()
        return HttpResponseRedirect(request.path_info)
    # curr_user=authority_db.objects.get(user=request.user)
    # curr_mail=request.user.email
    # curr_fn=request.user.first_name
    # curr_ln=request.user.last_name
    # curr_club=curr_user.club
    # #print(curr_mail,curr_club,curr_fn,curr_ln)
    # my_dict={'secy':curr_fn,'club':curr_club,'mail':curr_mail,'ln':curr_ln}
    return render(request,'pgi_app/check_status.html',context=req_dict)




@login_required
def oi_request(request):
    curr_username=request.user.username
    oi_name=request.user.first_name +" "+request.user.last_name
    curr_club=authority_db.objects.get(user=request.user).club
    user_name=str(authority_db.objects.get(club=curr_club,designation='Club secretary'))
    user_obj=User.objects.get(username=user_name)
    secy_email=user_obj.email
    secy_name=user_obj.first_name+" " +user_obj.last_name
    requests_by_user=request_db.objects.filter(authority=user_obj,status='0')
    req_dict={'requests':requests_by_user}
    if request.method=='POST':
        request_id_for_oi_acc=request.POST.get('accept_verdict')
        request_id_for_oi_dec=request.POST.get('decline_verdict')
        if request_id_for_oi_dec==None:
            req_for_oi=request_db.objects.get(request_id=request_id_for_oi_acc)
            curr_date=str(req_for_oi.date)
            curr_slot=str(req_for_oi.slot)
            curr_room=str(req_for_oi.room)
            req_for_oi.status=1
            req_for_oi.save()

            si_user_name=str(authority_db.objects.get(designation='Security In-charge'))
            si_user_obj=User.objects.get(username=si_user_name)
            si_email=si_user_obj.email
            si_name=si_user_obj.first_name+" "+si_user_obj.last_name


            message1='This is automated generated message. Please Don\'t reply to this.'+'\n'+'\n'+ 'Dear '+ secy_name+',\n'+'Your Club Office In-charge has accepted your room booking request for meeting/workshop and it has been forwarded to Security In-charge. You can login to PGI website to view it. Details of request are below. \n'+'\n'+'Club Office Incharge: '+ oi_name +'\n' + 'Club: '+curr_club +'\n' +'Date of booking: '+curr_date+'\n'+  'Slot of booking: '+curr_slot+'\n'+  'Venue of booking: '+curr_room+'\n'+ '\n'+ 'Thank You.'


            message2='This is automated generated message. Please Don\'t reply to this.'+'\n'+'\n'+ 'Dear '+ si_name+',\n'+'You have got a request for a room booking by one of the club secretaries for meeting/workshop. You can login to PGI website to either accept or decline it. Details of request are below. \n'+'\n'+ 'Club Secretary: '+ secy_name +'\n'   +'Club Office Incharge: '+ oi_name +'\n' + 'Club: '+curr_club +'\n' +'Date of booking: '+curr_date+'\n'+  'Slot of booking: '+curr_slot+'\n'+  'Venue of booking: '+curr_room+'\n'+ '\n'+ 'Thank You.'

            try:
                send_mail(
                'PGI Notification',
                message1,
                'akshitmonga6@gmail.com',
                [secy_email],
                fail_silently=False,
            )
            except:
                pass

            try:
                send_mail(
                'PGI Notification',
                message2,
                'akshitmonga6@gmail.com',
                [si_email],
                fail_silently=False,
            )
            except:
                pass





        else:
            req_for_oi=request_db.objects.get(request_id=request_id_for_oi_dec)
            req_for_oi.status=2
            req_for_oi.save()

            curr_date=str(req_for_oi.date)
            curr_slot=str(req_for_oi.slot)
            curr_room=str(req_for_oi.room)


            message3='This is automated generated message. Please Don\'t reply to this.'+'\n'+'\n'+ 'Dear '+ secy_name+',\n'+'Your Club Office In-charge has declined your room booking request for meeting/workshop. You can login to PGI website to view it. Details of request are below. \n'+'\n'+'Club Office Incharge: '+ oi_name +'\n' + 'Club: '+curr_club +'\n' +'Date of booking: '+curr_date+'\n'+  'Slot of booking: '+curr_slot+'\n'+  'Venue of booking: '+curr_room+'\n'+ '\n'+ 'Thank You.'


            try:
                send_mail(
                'PGI Notification',
                message3,
                'akshitmonga6@gmail.com',
                [secy_email],
                fail_silently=False,
            )
            except:
                pass






        return HttpResponseRedirect(request.path_info)
    return render(request,'pgi_app/oi_request.html',req_dict)




@login_required
def si_request(request):
    all_req=request_db.objects.filter(status='1')
    my_dict={}
    for i in all_req:
        user_obj=User.objects.get(username=str(i.authority))
        full_name=str(user_obj.first_name) + " " + str(user_obj.last_name)
        curr_club=authority_db.objects.get(user=user_obj).club
        my_dict[i]=(full_name,curr_club)

        guard_user_name=str(authority_db.objects.get(designation='Guard In-charge'))
        guard_user_obj=User.objects.get(username=guard_user_name)
        guard_email=guard_user_obj.email
        guard_name=guard_user_obj.first_name+" "+guard_user_obj.last_name

    req_dict={'requests':my_dict}
    if request.method=='POST':
        request_id_for_si_acc=request.POST.get('accept_verdict')

templates/pgi_app/available_rooms.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PGI</title>
    <link href="https://fonts.googleapis.com/css2?family=Kalam&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nothing+You+Could+Do&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "CSS/available_rooms.css" %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>



  <body>





    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a class="navbar-brand design" href="#"><b>PGI</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link  " href="{% url 'pgi_app:student_profile' %}">Profile <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'pgi_app:make_request' %}">Book</a>
          </li>


          <li class="nav-item">
            <a class="nav-link " href="{% url 'pgi_app:check_status' %}">Status</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'logout' %}">Logout</a>
          </li>

        </ul>
      </div>
      </nav>


<br>
<br>
<br>
<div class="container">

  <div class="alert alert-success pick" role="alert">
    <h4 class="alert-heading">Rooms available on <b>{{date}}</b> for slot <b>{{slot}}</b>.</h4>
  </div>

</div>

<br>




<form action = "{% url 'pgi_app:available_rooms' %}" method="POST">
  {%csrf_token%}
  <input type="hidden" name=date_hid value={{date}}>
  <input type="hidden" name=slot_hid value={{slot}}>

  <div class="container">

    <table class="table table-hover my_table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Room</th>
          <th scope="col">Location</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {%for key,value in rooms_show.items %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{key}}</td>
          <td>{{value}}</td>
          <td><button type="submit" class="btn btn-success" name=room_booked value="{{key}}" >Book</button></td>


        </tr>
        {% endfor %}
      </tbody>
    </table>






  </div>






</form>





















  </body>
</html>

templates/pgi_app/check_status.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PGI</title>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nothing+You+Could+Do&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "CSS/check_status.css" %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>



  <body>





    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a class="navbar-brand design" href="#"><b>PGI</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link  " href="{% url 'pgi_app:student_profile' %}">Profile <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'pgi_app:make_request' %}">Book</a>
          </li>


          <li class="nav-item">
            <a class="nav-link " href="{% url 'pgi_app:check_status' %}">Status</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'logout' %}">Logout</a>
          </li>

        </ul>
      </div>
    </nav>



<br>
<br>
<br>
<div class="container">

  <div class="alert alert-success pick" role="alert">
    <h4 class="alert-heading">Check how far your requests have gone!</h4>
  </div>

</div>


<br>



<form action = "{% url 'pgi_app:check_status' %}" method="POST">
  {%csrf_token%}


  <div class="container">

    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Slot</th>
          <th scope="col">Room</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {%for i in requests%}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{i.date}}</td>
          <td>{{i.slot}}</td>
          <td>{{i.room}}</td>
          {% if i.status == '0' %}
          <td>Pending</td>
          {% elif i.status == '1' %}
          <td>Approved by OI (Pending)</td>
          {% elif i.status == '2' %}
          <td>Rejected by OI (Cancelled)</td>
          {% elif i.status == '3' %}
          <td>Approved by SI (Accepted)</td>
          {% elif i.status == '4' %}
          <td>Rejected by SI (Cancelled)</td>
          {%endif%}
          <td>
            {% if i.status == '0' or i.status == '1' %}
            <button type="submit" class="btn btn-danger" name=cancel value="{{i.request_id}}"  >Cancel</button>

            {% else %}
            <a href="#" class="btn btn-danger disabled " role="button" aria-disabled="true">Cancel</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>






  </div>






</form>











  </body>
</html>

templates/pgi_app/guard_request.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PGI</title>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nothing+You+Could+Do&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "CSS/guard_request_p.css" %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>



  <body>





    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a class="navbar-brand design" href="#"><b>PGI</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link  " href="{% url 'pgi_app:guard_profile' %}">Profile <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link " href="{% url 'pgi_app:guard_request' %}">Bookings</a>
      </li>


      <li class="nav-item">
        <a class="nav-link " href="{% url 'logout' %}" >Logout</a>
      </li>

    </ul>
  </div>
</nav>


<br>
<br>
<br>
<div class="container">

  <div class="alert alert-success pick" role="alert">
    <h4 class="alert-heading">The Sectretaries of all Clubs have made following room bookings which are accepted by esteemed Security In-charge.</h4>
  </div>

</div>


<br>


<form action = "{% url 'pgi_app:si_request' %}" method="POST">
  {%csrf_token%}


  <div class="container">

    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Slot</th>
          <th scope="col">Room</th>
          <th scope="col">Club</th>
          <th scope="col">Secretary</th>
        </tr>
      </thead>
      <tbody>
        {%for key,value in requests.items%}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{key.date}}</td>
          <td>{{key.slot}}</td>
          <td>{{key.room}}</td>
          {%for i in value%}
            <td>{{i}}</td>
          {%endfor%}

        </tr>
        {% endfor %}
      </tbody>
    </table>






  </div>






</form>











  </body>
</html>